docker-compose-yaml: docker-compose.yml
environments:
  main:
    routes:
      - nginx:
        - marco-test.test6.amazee.io
        - foo5.marco-test6.amazeeio.review
        - foo6.marco-test6.amazeeio.review
        - foo7.marco-test6.amazeeio.review
        - foo8.marco-test6.amazeeio.review
        - foo9.marco-test6.amazeeio.review
        - foo10.marco-test6.amazeeio.review