docker-compose-yaml: docker-compose.yml
environments:
  main:
    routes:
      - nginx:
        - marco-test.test6.amazee.io
        - foo7.marco-test6.amazeeio.review
        - foo8.marco-test6.amazeeio.review
        - foo9.marco-test6.amazeeio.review
        - foo10.marco-test6.amazeeio.review
        - foo11.marco-test6.amazeeio.review
        - foo12.marco-test6.amazeeio.review
        - foo13.marco-test6.amazeeio.review
        - foo14.marco-test6.amazeeio.review
        - foo15.marco-test6.amazeeio.review