docker-compose-yaml: docker-compose.yml
environments:
  main:
    routes:
      - nginx:
        - marco-test.test6.amazee.io
        - foo3.marco-test6.amazeeio.review
        - foo4.marco-test6.amazeeio.review