docker-compose-yaml: docker-compose.yml
environments:
  main:
    routes:
      - nginx:
        - marco-test.test6.amazee.io
        - foo.marco-test6.amazeeio.review
        - foo.test6.amazeeio.review
